# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: vs2017-win2016
  demands: DotNetFramework

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 2.2.104'
  inputs:
    version: 2.2.104

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.0.100'
  inputs:
    version: 3.0.100

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**\*.sln'
    arguments: '-c Release  -p:Platform=x64'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**\*.sln'
    arguments: '-c Release  -p:Platform=x64  --no-build --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: '**/*.sln'
    configuration: Release
    nobuild: true
    buildProperties: 'IsReleaseBuild=false'
