# Pull request validation pipeline
# More information on available tasks: https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: vs2017-win2016
  demands: DotNetFramework


steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 2.2'
  inputs:
    version: 2.2.x

- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.x'
  inputs:
    version: 3.x

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    projects: '**\*.sln'
    arguments: '-c Release  -p:Platform=x64'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**\*.sln'
    arguments: '-c Release  -p:Platform=x64  --no-build --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    packagesToPack: '**/*.sln'
    configuration: Release
    nobuild: true
    buildProperties: 'IsReleaseBuild=false'
